GET http://localhost:3000/

###

GET  http://localhost:3000/items

###

GET http://localhost:3000/items/item
Content-Type: application/json

{
    "itemId": "607b1bbaecf6ea37a8284e24"
}

###

GET  http://localhost:3000/img/pokemon-rojo.jpg

###

POST http://localhost:3000/items
Content-Type: application/json

{
    "title": "Sensor DTH11",
    "price": 50.00,
    "image": "DHT11.jpg"
}

###

POST http://localhost:3000/create-payment-intent
Content-Type: application/json

[
    {
        "id": "607b1bbaecf6ea37a8284e24",
        "qty": 2
    }
]